# Generated by Django 2.0.10 on 2019-01-31 13:28

import DjangoUeditor.models
import articles.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('abstract', models.CharField(blank=True, default='这篇文章没有摘要', max_length=120, verbose_name='文章摘要')),
                ('front_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='articles/%Y/%m/', verbose_name='文章封面')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容')),
                ('word_count', models.IntegerField(default=0, verbose_name='文章字数')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击量')),
                ('favor_number', models.IntegerField(default=0, verbose_name='收藏量')),
                ('comment_number', models.IntegerField(default=0, verbose_name='评论量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='类别名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='标签名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(articles.models.get_sentinel_category), to='articles.ArticleCategory', verbose_name='文章类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.ArticleTag', verbose_name='文章标签'),
        ),
    ]
