# Generated by Django 2.0.10 on 2019-02-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='abstract',
            new_name='brief',
        ),
    ]
