# Generated by Django 2.0.10 on 2019-02-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmcategory',
            name='code',
            field=models.CharField(default='', help_text='类别缩写', max_length=30, verbose_name='类别缩写'),
        ),
        migrations.AlterField(
            model_name='algorithmcategory',
            name='description',
            field=models.TextField(default='该类别暂无描述信息...', help_text='类别描述', verbose_name='类别描述'),
        ),
    ]
