# Generated by Django 2.0.10 on 2019-02-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_auto_20190201_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmimage',
            name='algorithm',
        ),
        migrations.DeleteModel(
            name='AlgorithmImage',
        ),
    ]
